# Example configuration file for TeleMikiya

[telegram]
# Telegram API ID (obtain from https://my.telegram.org)
api_id = 100000
# Telegram API Hash (obtain from https://my.telegram.org)
api_hash = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
# Your Telegram account phone number
phone_number = "+12345678900"
# List of dialog IDs to observe and index messages from
# Leave empty to observe all accessible dialogs
observed_dialog_ids = []
# Dialog info update interval
dialog_update_interval = "24h"
# Telegram Bot Token (obtain from @BotFather)
bot_token = "1234567890:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
# List of Telegram user IDs allowed to use the bot
bot_allowed_user_ids = [123456789]

[database]
# PostgreSQL database host
host = "localhost"
# PostgreSQL database port
port = 5432
# PostgreSQL SSL mode: "disable", "require", "verify-ca", or "verify-full"
ssl_mode = "disable"
# Database connection timeout (optional)
connect_timeout = "1h"
# PostgreSQL database username
user = "telemikiya"
# PostgreSQL database password
password = "telemikiya"
# PostgreSQL database name
db_name = "telemikiya"

[embedding]
# Embedding provider: "ollama", "openai", or "google"
provider = "ollama"
# Embedding service API endpoint
base_url = "http://localhost:11434"
# Request timeout duration (optional)
timeout = "30s"
# Batch size (number of messages to process per batch)
batch_size = 10
# Embedding model name
model = "snowflake-arctic-embed2:568m"
# Embedding vector dimensions
dimensions = 1024

# Ollama specific settings
[embedding.ollama]
# API connection keep-alive duration (optional)
keep_alive = "5m"
# Model parameters (optional)
model_parameters = {}

# OpenAI specific settings
[embedding.openai]
# OpenAI API key
api_key = ""
# OpenAI organization ID (optional)
organization = ""
# OpenAI project (optional)
project = ""

# Google specific settings
[embedding.google]
# Google API key
api_key = ""
# Google quota project ID (optional)
quota_project = ""
